image: maven:3-jdk-8

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install openssh-client sshpass --yes

build:
  script:
   - mvn package -B

deploy:
  script:
   - mvn clean package -B
   - sshpass -p $password ssh -o StrictHostKeyChecking=no $user@$hostname 'rm ~/plan.jar'
   - sshpass -p $password scp -o StrictHostKeyChecking=no target/plan.jar $user@$hostname:~/.
   - sshpass -p $password ssh -o StrictHostKeyChecking=no $user@$hostname '~/reloadplan.sh'
